### ISSUE TITLE
Exclude pt_PT translation pulls from Transifiex

### ISSUE THREAD

**Issue by devinsays** [devinsays/portfolio-press#102]
Need to update the Grunt task to somehow exclude these.

@pedro-mendonca is going to submit through GitHub instead.

**Comment by pedro-mendonca** [comment]
Meanwhile I'll keep uploading the .po as new resource to Transifex for further reference to other translators. It's easy to track differences in Git and easy to batch upload to Transifex.
I've also updated pt_PT here with new PR.
Thanks for your atention on this.

**Comment by devinsays** [comment]
@pedro-mendonca I am going to drop Transifex for this project now that WordPress.org has its own translation tools.

https://translate.wordpress.org/locale/pt-br/default/wp-themes/portfolio-press

**Comment by pedro-mendonca** [comment]
Hi,
I totally agree on that!
I'm using it for a while now.
https://translate.wordpress.org/locale/pt/default/wp-themes/portfolio-press (pt, not pt-br)
